/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface FlashbotsCheckAndSendInterface extends ethers.utils.Interface {
  functions: {
    "check32BytesAndSend(address,bytes,bytes32)": FunctionFragment;
    "check32BytesAndSendMulti(address[],bytes[],bytes32[])": FunctionFragment;
    "checkBytesAndSend(address,bytes,bytes)": FunctionFragment;
    "checkBytesAndSendMulti(address[],bytes[],bytes[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "check32BytesAndSend",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "check32BytesAndSendMulti",
    values: [string[], BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "checkBytesAndSend",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkBytesAndSendMulti",
    values: [string[], BytesLike[], BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "check32BytesAndSend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "check32BytesAndSendMulti",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkBytesAndSend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkBytesAndSendMulti",
    data: BytesLike
  ): Result;

  events: {};
}

export class FlashbotsCheckAndSend extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: FlashbotsCheckAndSendInterface;

  functions: {
    check32BytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "check32BytesAndSend(address,bytes,bytes32)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    check32BytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "check32BytesAndSendMulti(address[],bytes[],bytes32[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    checkBytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "checkBytesAndSend(address,bytes,bytes)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    checkBytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "checkBytesAndSendMulti(address[],bytes[],bytes[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  check32BytesAndSend(
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "check32BytesAndSend(address,bytes,bytes32)"(
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  check32BytesAndSendMulti(
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "check32BytesAndSendMulti(address[],bytes[],bytes32[])"(
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  checkBytesAndSend(
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "checkBytesAndSend(address,bytes,bytes)"(
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  checkBytesAndSendMulti(
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "checkBytesAndSendMulti(address[],bytes[],bytes[])"(
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    check32BytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "check32BytesAndSend(address,bytes,bytes32)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    check32BytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "check32BytesAndSendMulti(address[],bytes[],bytes32[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    checkBytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "checkBytesAndSend(address,bytes,bytes)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    checkBytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "checkBytesAndSendMulti(address[],bytes[],bytes[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    check32BytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "check32BytesAndSend(address,bytes,bytes32)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    check32BytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "check32BytesAndSendMulti(address[],bytes[],bytes32[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    checkBytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "checkBytesAndSend(address,bytes,bytes)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    checkBytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "checkBytesAndSendMulti(address[],bytes[],bytes[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    check32BytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "check32BytesAndSend(address,bytes,bytes32)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    check32BytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "check32BytesAndSendMulti(address[],bytes[],bytes32[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    checkBytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "checkBytesAndSend(address,bytes,bytes)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    checkBytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "checkBytesAndSendMulti(address[],bytes[],bytes[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
