/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MevBriberInterface extends ethers.utils.Interface {
  functions: {
    "PERMIT_TYPEHASH()": FunctionFragment;
    "WETH()": FunctionFragment;
    "briberPermitted(address,address,uint256,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "check32BytesAndSend(address,bytes,bytes32)": FunctionFragment;
    "check32BytesAndSendMulti(address[],bytes[],bytes32[])": FunctionFragment;
    "check32BytesAndSendMultiWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address[],bytes[],bytes32[])": FunctionFragment;
    "check32BytesAndSendWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address,bytes,bytes32)": FunctionFragment;
    "checkBytesAndSend(address,bytes,bytes)": FunctionFragment;
    "checkBytesAndSendMulti(address[],bytes[],bytes[])": FunctionFragment;
    "checkBytesAndSendMultiWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address[],bytes[],bytes[])": FunctionFragment;
    "checkBytesAndSendWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address,bytes,bytes)": FunctionFragment;
    "nonces(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "PERMIT_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "briberPermitted",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "check32BytesAndSend",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "check32BytesAndSendMulti",
    values: [string[], BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "check32BytesAndSendMultiWETH",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      string[],
      BytesLike[],
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "check32BytesAndSendWETH",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      string,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "checkBytesAndSend",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkBytesAndSendMulti",
    values: [string[], BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "checkBytesAndSendMultiWETH",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      string[],
      BytesLike[],
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "checkBytesAndSendWETH",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      string,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "PERMIT_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "briberPermitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "check32BytesAndSend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "check32BytesAndSendMulti",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "check32BytesAndSendMultiWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "check32BytesAndSendWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkBytesAndSend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkBytesAndSendMulti",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkBytesAndSendMultiWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkBytesAndSendWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;

  events: {
    "Bribed(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Bribed"): EventFragment;
}

export class MevBriber extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MevBriberInterface;

  functions: {
    PERMIT_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "PERMIT_TYPEHASH()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    WETH(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "WETH()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    briberPermitted(
      owner: string,
      spender: string,
      value: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "briberPermitted(address,address,uint256,uint256,uint8,bytes32,bytes32)"(
      owner: string,
      spender: string,
      value: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    check32BytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "check32BytesAndSend(address,bytes,bytes32)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    check32BytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "check32BytesAndSendMulti(address[],bytes[],bytes32[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    check32BytesAndSendMultiWETH(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "check32BytesAndSendMultiWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address[],bytes[],bytes32[])"(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    check32BytesAndSendWETH(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "check32BytesAndSendWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address,bytes,bytes32)"(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    checkBytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "checkBytesAndSend(address,bytes,bytes)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    checkBytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "checkBytesAndSendMulti(address[],bytes[],bytes[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    checkBytesAndSendMultiWETH(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "checkBytesAndSendMultiWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address[],bytes[],bytes[])"(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    checkBytesAndSendWETH(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "checkBytesAndSendWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address,bytes,bytes)"(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    nonces(
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "nonces(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;
  };

  PERMIT_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  "PERMIT_TYPEHASH()"(overrides?: CallOverrides): Promise<string>;

  WETH(overrides?: CallOverrides): Promise<string>;

  "WETH()"(overrides?: CallOverrides): Promise<string>;

  briberPermitted(
    owner: string,
    spender: string,
    value: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "briberPermitted(address,address,uint256,uint256,uint8,bytes32,bytes32)"(
    owner: string,
    spender: string,
    value: BigNumberish,
    deadline: BigNumberish,
    v: BigNumberish,
    r: BytesLike,
    s: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  check32BytesAndSend(
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "check32BytesAndSend(address,bytes,bytes32)"(
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  check32BytesAndSendMulti(
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "check32BytesAndSendMulti(address[],bytes[],bytes32[])"(
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  check32BytesAndSendMultiWETH(
    _owner: string,
    _spender: string,
    _value: BigNumberish,
    _deadline: BigNumberish,
    _v: BigNumberish,
    _r: BytesLike,
    _s: BytesLike,
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "check32BytesAndSendMultiWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address[],bytes[],bytes32[])"(
    _owner: string,
    _spender: string,
    _value: BigNumberish,
    _deadline: BigNumberish,
    _v: BigNumberish,
    _r: BytesLike,
    _s: BytesLike,
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  check32BytesAndSendWETH(
    _owner: string,
    _spender: string,
    _value: BigNumberish,
    _deadline: BigNumberish,
    _v: BigNumberish,
    _r: BytesLike,
    _s: BytesLike,
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "check32BytesAndSendWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address,bytes,bytes32)"(
    _owner: string,
    _spender: string,
    _value: BigNumberish,
    _deadline: BigNumberish,
    _v: BigNumberish,
    _r: BytesLike,
    _s: BytesLike,
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  checkBytesAndSend(
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "checkBytesAndSend(address,bytes,bytes)"(
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  checkBytesAndSendMulti(
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "checkBytesAndSendMulti(address[],bytes[],bytes[])"(
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  checkBytesAndSendMultiWETH(
    _owner: string,
    _spender: string,
    _value: BigNumberish,
    _deadline: BigNumberish,
    _v: BigNumberish,
    _r: BytesLike,
    _s: BytesLike,
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "checkBytesAndSendMultiWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address[],bytes[],bytes[])"(
    _owner: string,
    _spender: string,
    _value: BigNumberish,
    _deadline: BigNumberish,
    _v: BigNumberish,
    _r: BytesLike,
    _s: BytesLike,
    _targets: string[],
    _payloads: BytesLike[],
    _resultMatches: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  checkBytesAndSendWETH(
    _owner: string,
    _spender: string,
    _value: BigNumberish,
    _deadline: BigNumberish,
    _v: BigNumberish,
    _r: BytesLike,
    _s: BytesLike,
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "checkBytesAndSendWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address,bytes,bytes)"(
    _owner: string,
    _spender: string,
    _value: BigNumberish,
    _deadline: BigNumberish,
    _v: BigNumberish,
    _r: BytesLike,
    _s: BytesLike,
    _target: string,
    _payload: BytesLike,
    _resultMatch: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  nonces(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

  "nonces(address)"(
    owner: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    PERMIT_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    "PERMIT_TYPEHASH()"(overrides?: CallOverrides): Promise<string>;

    WETH(overrides?: CallOverrides): Promise<string>;

    "WETH()"(overrides?: CallOverrides): Promise<string>;

    briberPermitted(
      owner: string,
      spender: string,
      value: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "briberPermitted(address,address,uint256,uint256,uint8,bytes32,bytes32)"(
      owner: string,
      spender: string,
      value: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    check32BytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "check32BytesAndSend(address,bytes,bytes32)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    check32BytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "check32BytesAndSendMulti(address[],bytes[],bytes32[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    check32BytesAndSendMultiWETH(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "check32BytesAndSendMultiWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address[],bytes[],bytes32[])"(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    check32BytesAndSendWETH(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "check32BytesAndSendWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address,bytes,bytes32)"(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    checkBytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "checkBytesAndSend(address,bytes,bytes)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    checkBytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "checkBytesAndSendMulti(address[],bytes[],bytes[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    checkBytesAndSendMultiWETH(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "checkBytesAndSendMultiWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address[],bytes[],bytes[])"(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    checkBytesAndSendWETH(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "checkBytesAndSendWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address,bytes,bytes)"(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    nonces(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "nonces(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    Bribed(
      briber: string | null,
      miner: string | null,
      amount: null
    ): EventFilter;
  };

  estimateGas: {
    PERMIT_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    "PERMIT_TYPEHASH()"(overrides?: CallOverrides): Promise<BigNumber>;

    WETH(overrides?: CallOverrides): Promise<BigNumber>;

    "WETH()"(overrides?: CallOverrides): Promise<BigNumber>;

    briberPermitted(
      owner: string,
      spender: string,
      value: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "briberPermitted(address,address,uint256,uint256,uint8,bytes32,bytes32)"(
      owner: string,
      spender: string,
      value: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    check32BytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "check32BytesAndSend(address,bytes,bytes32)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    check32BytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "check32BytesAndSendMulti(address[],bytes[],bytes32[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    check32BytesAndSendMultiWETH(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "check32BytesAndSendMultiWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address[],bytes[],bytes32[])"(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    check32BytesAndSendWETH(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "check32BytesAndSendWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address,bytes,bytes32)"(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    checkBytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "checkBytesAndSend(address,bytes,bytes)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    checkBytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "checkBytesAndSendMulti(address[],bytes[],bytes[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    checkBytesAndSendMultiWETH(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "checkBytesAndSendMultiWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address[],bytes[],bytes[])"(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    checkBytesAndSendWETH(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "checkBytesAndSendWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address,bytes,bytes)"(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    nonces(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "nonces(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    PERMIT_TYPEHASH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "PERMIT_TYPEHASH()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    WETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "WETH()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    briberPermitted(
      owner: string,
      spender: string,
      value: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "briberPermitted(address,address,uint256,uint256,uint8,bytes32,bytes32)"(
      owner: string,
      spender: string,
      value: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    check32BytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "check32BytesAndSend(address,bytes,bytes32)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    check32BytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "check32BytesAndSendMulti(address[],bytes[],bytes32[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    check32BytesAndSendMultiWETH(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "check32BytesAndSendMultiWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address[],bytes[],bytes32[])"(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    check32BytesAndSendWETH(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "check32BytesAndSendWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address,bytes,bytes32)"(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    checkBytesAndSend(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "checkBytesAndSend(address,bytes,bytes)"(
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    checkBytesAndSendMulti(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "checkBytesAndSendMulti(address[],bytes[],bytes[])"(
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    checkBytesAndSendMultiWETH(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "checkBytesAndSendMultiWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address[],bytes[],bytes[])"(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _targets: string[],
      _payloads: BytesLike[],
      _resultMatches: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    checkBytesAndSendWETH(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "checkBytesAndSendWETH(address,address,uint256,uint256,uint8,bytes32,bytes32,address,bytes,bytes)"(
      _owner: string,
      _spender: string,
      _value: BigNumberish,
      _deadline: BigNumberish,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _target: string,
      _payload: BytesLike,
      _resultMatch: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    nonces(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "nonces(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
